"""Параметры лабораторной работы."""

SAMPLE_RATE_HZ = 100
SAMPLES_PER_SIGNAL = 10_000
SIGNAL_DURATION_S = SAMPLES_PER_SIGNAL / SAMPLE_RATE_HZ
KAGGLE_DATASET = "ahmadsaeed1007/ecg-signal"
ECG_DAT_FILENAME = "ECG.dat"
SSA_WINDOW_LENGTH = 300
SSA_MAX_COMPONENTS = 30
HR_MIN_BPM = 40
HR_MAX_BPM = 220

# Окно для крупных графиков временного ряда (с)
PLOT_ZOOM_SECONDS = 1.0
PLOT_OVERVIEW_SECONDS = 30.0